version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./"
    schedule:
      interval: "daily"
      time: "08:00"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]