name: Lint Angular App

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository


      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./client
        run: npm install

      # Step 4: Run linting
      - name: Run linting
        working-directory: ./client
        run: npm run lint

      - name: Run style lint
        working-directory: ./client
        run: npm run style-lint

      - name: Run prettier
        working-directory: ./client
        run: npm run prettier-fix
